###
GET https://server.aptech.io/training/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR1bmdudCIsImlhdCI6MTY1NTM3NzA3MiwiZXhwIjoxNjU1MzgwNjcyfQ.vGEvJ5t4vb7mMDGyhME63csgwM2kchtZVsuF8NkZ5AM